server:
  servlet:
    context-path: /
  port: 8080

spring:
  main:
    web-application-type: reactive

  profiles:
    group:
      "local": "local,gateway-secret"
      "dev": "dev,gateway-secret"
    default: local
