server:
  servlet:
    context-path: /
  port: 8080

spring:
  main:
    web-application-type: reactive

  profiles:
    group:
      "local": "local,secret"
      "dev": "dev,secret"
    default: dev

  cloud:
    gateway:
      routes:
        - id: auth-service-delete
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/member
            - Method=DELETE
          filters:
            - JwtAuthentication=ROLE_USER

        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

        - id: member-service-docs
          uri: http://localhost:8082
          predicates:
            - Path=/api/members/swagger-ui.html, /api/members/v3/api-docs

        - id: member-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/members/**
          filters:
            - JwtAuthentication=ROLE_USER

        - id: team-service-docs
          uri: http://localhost:8083
          predicates:
            - Path=/api/teams/swagger-ui.html, /api/teams/v3/api-docs

        - id: team-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/teams/**
          filters:
            - JwtAuthentication=ROLE_USER

        - id: thread-service-docs
          uri: http://localhost:8084
          predicates:
            - Path=/api/threads/swagger-ui.html, /api/threads/v3/api-docs

        - id: thread-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/threads/**
          filters:
            - JwtAuthentication=ROLE_USER

        - id: search-service-docs
          uri: http://localhost:8085
          predicates:
            - Path=/api/search/swagger-ui.html, /api/search/v3/api-docs

        - id: search-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/search/**
          filters:
            - JwtAuthentication=ROLE_USER