spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:tcp://localhost:8075/~/h2/member
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    database-platform:
    show-sql: true
    database: h2
    properties:
      hibernate:
        format_sql: true
  localhost: localhost
  main:
    allow-circular-references: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka

springdoc:
  api-docs:
    path: /api/members/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /api/members/swagger-ui.html

# open api setting
openapi:
  service:
    title: member-service doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:8080 #api gateway url