spring:
  config:
    activate:
      on-profile: prod
  application:
    name: member-service
  datasource:
    url: jdbc:mysql://garamgaebee-rds.cmvufjnyvp1f.ap-northeast-2.rds.amazonaws.com:3306/member
    username: admin
    password: garamgaebeebackend!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: MySQL8Dialect
    show-sql: false
    database: mysql
    properties:
      hibernate:
        format_sql: true
  localhost: host.docker.internal

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://host.docker.internal:9000/eureka
# open api setting
openapi:
  service:
    title: member-service doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://host.docker.internal:8080 #api gateway url