server:
  port: 8082

spring:
  profiles:
    group:
      "local" : "local"
      "dev" : "dev,member-rds"
      "prod" : "prod, member-rds"
    default: local

  application:
    name: member-service