spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    database-platform: MySQL8Dialect
    show-sql: false
    database: mysql
    properties:
      hibernate:
        format_sql: true
  localhost: host.docker.internal
  main:
    allow-circular-references: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://host.docker.internal:9000/eureka
