spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://garamgaebee-rds.cmvufjnyvp1f.ap-northeast-2.rds.amazonaws.com:3306/memberdev
    username: admin
    password: garamgaebeebackend!!
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format_sql: true
  localhost: host.docker.internal

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://host.docker.internal:9000/eureka
# open api setting
openapi:
  service:
    title: member-service doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: https://dev.garamgaebee.shop #api gateway url