spring:
  config:
    activate:
      on-profile: local
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:9000/eureka/}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
  config:
    activate:
      on-profile: dev
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://host.docker.internal:9000/eureka/}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}