cloud:
  aws:
    credentials:
      access-key: AKIAXBBCDFFJXYVXAM7V
      secret-key: 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
    s3: #버킷이름
      bucket: garamgaebee
      path: dev
      distribution: https://garamgaebee.ap-northeast-2.amazonaws.com
    region: #S3 지역
      static: ap-northeast-2
    stack:
      auto: false
    front-cloud:
      distribution: https://d19lrfp6d3l9uc.cloudfront.net
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB