server:
  port: 8081

spring:
  profiles:
    group:
      "local" : "local,secret"
      "dev" : "dev,rds,secret"
    default: dev

  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:9000/eureka/}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoint:
    shutdown:
      enabled: true