spring:
  data:
    redis:
      host: localhost
      port: 6379

oauth2:
  user:
    kakao:
      client-id: temp
      client-secret: temp
      redirect-uri: temp
  provider:
    kakao:
      token-uri: temp
      user-info-uri: temp

jwt:
  token:
    secret-key: secret_key
  access-token:
    expired-time: 3600000
  refresh-token:
    expired-time: 1209600000