logging.level:
  org.hibernate.SQL: debug

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        fotmat_sql: true
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379

oauth2:
  user:
    kakao:
      client-id: cd3d57b0d96c1ddde8ccbfdb7d8cab2e
      client-secret: I6QLvFVJstrs48clLlOpGavIT0DOsLe7
      redirect-uri: http://localhost:8080/redirect/auth
  provider:
    kakao:
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me

jwt:
  token:
    secret-key: secret_key
  access-token:
    expired-time: 3600000
  refresh-token:
    expired-time: 1209600000