
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        fotmat_sql: true

  data:
    redis:
      host: localhost
      port: 6379

logging.level:
  org.hibernate.SQL: debug

# open api setting
openapi:
  service:
    title: auth-service doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:8080 #api gateway url
springdoc:
  api-docs:
    path: /api/auth/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /api/auth/swagger-ui.html