server:
  port: 8081

logging.level:
  org.hibernate.SQL: debug

spring:
  application:
    name: auth-service

  datasource:
    url: 'jdbc:h2:tcp://localhost/~/test'
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        fotmat_sql: true
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  # mail setting
  mail:
    host: smtp.gmail.com
    port: 587
    username: tjrcjs0705@gmail.com # 수정
    password: xacekpcwamofxujq # 수정
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

oauth2:
  user:
    kakao:
      client-id: cd3d57b0d96c1ddde8ccbfdb7d8cab2e
      client-secret: I6QLvFVJstrs48clLlOpGavIT0DOsLe7
      redirect-uri: http://localhost:8080/redirect/auth
  provider:
    kakao:
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me

jwt:
  token:
    secret-key: secret_key
  access-token:
    expired-time: 3600000
  refresh-token:
    expired-time: 1209600000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:9000/eureka/}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoint:
    shutdown:
      enabled: true