server:
  port: 8084

spring:
  profiles:
    group:
      "local" : "local"
      "dev" : "dev,thread-rds"
      "prod" : "prod, thread-rds"
    default: local

  application:
    name: thread-service