server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka

# open api setting
openapi:
  service:
    title: thread-service doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:8080 #api gateway url
springdoc:
  api-docs:
    path: /api/threads/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /api/threads/swagger-ui.html

spring:
  profiles:
    active: local
  application:
    name: thread-service
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/thread
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform:
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  main:
    allow-circular-references: true

---

spring:
  profiles:
    active: dev
  application:
    name: thread-service
  datasource:
    url: jdbc:mysql://garamgaebee-rds.cmvufjnyvp1f.ap-northeast-2.rds.amazonaws.com:3306/threaddev
    username: admin
    password: garamgaebeebackend!!
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform:
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  main:
    allow-circular-references: true

---

spring:
  profiles:
    active: prod
  application:
    name: thread-service
  datasource:
    url: jdbc:mysql://garamgaebee-rds.cmvufjnyvp1f.ap-northeast-2.rds.amazonaws.com:3306/thread
    username: admin
    password: garamgaebeebackend!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform:
    show-sql: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  main:
    allow-circular-references: true