server:
  port: 8082

spring:
  application:
    name: threadservice
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/thread
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform:
    show-sql: true

  main:
    allow-circular-references: true