spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform:
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  main:
    allow-circular-references: true

  localhost: host.docker.internal
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://host.docker.internal:9000/eureka

springdoc:
  api-docs:
    path: /api/threads/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /api/threads/swagger-ui.html

# open api setting
openapi:
  service:
    title: thread-service doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: https://dev.garamgaebee.shop #api gateway url